[build]
  command = "echo 'Build complete'"
  publish = "public"
  environment = { NODE_VERSION = "18" } # This tells Netlify to use Node.js 18

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react", "react-dom"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
